services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_app
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "${PORT}:5000"
    depends_on:
      - db
    command: npm start

volumes:
  db_data:
